/**
 * Equipment and Coffee Seed Data
 *
 * This file contains curated data for popular specialty coffee equipment
 * and Costco whole bean coffees, researched from official sources and
 * reputable coffee authority databases.
 *
 * Run this script to populate a user's Firebase collections.
 */

// ============================================================================
// BREWERS - Top 20 Specialty Coffee Brewers (Non-Auto Drip)
// ============================================================================

export const brewersData = [
  // Pour Over Drippers
  {
    name: "V60 02",
    brand: "Hario",
    type: "pour-over",
    material: "Ceramic",
    capacityMl: 500,
    filterType: "paper",
    notes: "Iconic 60° cone angle with spiral ribs. Produces bright, clean cups with excellent clarity. The most popular size for 1-4 cups. Uses V60 02 paper filters.",
  },
  {
    name: "V60 01",
    brand: "Hario",
    type: "pour-over",
    material: "Plastic",
    capacityMl: 300,
    filterType: "paper",
    notes: "Compact single-cup version. Heat-retaining plastic is ideal for travel. Same 60° design as the 02.",
  },
  {
    name: "V60 03",
    brand: "Hario",
    type: "pour-over",
    material: "Glass",
    capacityMl: 1000,
    filterType: "paper",
    notes: "Largest V60 size for brewing 1-6 cups. Elegant borosilicate glass construction.",
  },
  {
    name: "Classic 6-Cup",
    brand: "Chemex",
    type: "pour-over",
    material: "Glass",
    capacityMl: 880,
    filterType: "paper",
    notes: "Iconic hourglass design from 1941. Uses thick bonded filters for exceptionally clean, bright cups. Part of MoMA's permanent collection. 30oz capacity.",
  },
  {
    name: "Classic 8-Cup",
    brand: "Chemex",
    type: "pour-over",
    material: "Glass",
    capacityMl: 1180,
    filterType: "paper",
    notes: "Most popular Chemex size. 40oz capacity, perfect for entertaining. Polished wood collar with rawhide tie.",
  },
  {
    name: "Classic 3-Cup",
    brand: "Chemex",
    type: "pour-over",
    material: "Glass",
    capacityMl: 440,
    filterType: "paper",
    notes: "Compact 15oz Chemex for 1-2 cups. Uses half-moon filters. Same clean, bright cup profile.",
  },
  {
    name: "Wave 185",
    brand: "Kalita",
    type: "pour-over",
    material: "Stainless Steel",
    capacityMl: 750,
    filterType: "paper",
    notes: "Flat-bottom dripper with 3 small holes for even extraction. 20-wave filter design limits contact. For 2-4 cups. Made in Japan.",
  },
  {
    name: "Wave 155",
    brand: "Kalita",
    type: "pour-over",
    material: "Stainless Steel",
    capacityMl: 300,
    filterType: "paper",
    notes: "Single-cup Kalita Wave. Forgiving flat-bottom design produces consistent, balanced cups.",
  },
  {
    name: "Dripper M",
    brand: "Origami",
    type: "pour-over",
    material: "Ceramic",
    capacityMl: 600,
    filterType: "paper",
    notes: "Japanese Mino-ware ceramic with 20 ribs. Compatible with both conical (V60) and wave (Kalita) filters. For 1-4 cups.",
  },
  {
    name: "Dripper Air S",
    brand: "Origami",
    type: "pour-over",
    material: "Plastic",
    capacityMl: 300,
    filterType: "paper",
    notes: "Lightweight AS resin version. 50% lighter than ceramic. Dishwasher safe. Uses V60 01 or Wave 155 filters.",
  },

  // Immersion Brewers
  {
    name: "AeroPress Original",
    brand: "AeroPress",
    type: "immersion",
    material: "Plastic",
    capacityMl: 295,
    filterType: "paper",
    notes: "Versatile immersion/pressure brewer. Makes 1-3 cups in under 2 minutes. BPA-free polypropylene. Invented by Aerobie's Alan Adler in 2005.",
  },
  {
    name: "AeroPress Go",
    brand: "AeroPress",
    type: "immersion",
    material: "Plastic",
    capacityMl: 237,
    filterType: "paper",
    notes: "Travel-optimized AeroPress with included mug/lid. 8oz capacity. Compact and self-contained.",
  },
  {
    name: "AeroPress XL",
    brand: "AeroPress",
    type: "immersion",
    material: "Plastic",
    capacityMl: 590,
    filterType: "paper",
    notes: "Double-capacity AeroPress for 20oz brews. Same versatile brewing, bigger batches.",
  },
  {
    name: "Clever Dripper Large",
    brand: "Clever",
    type: "immersion",
    material: "Plastic",
    capacityMl: 530,
    filterType: "paper",
    notes: "Immersion dripper with valve release. Uses standard #4 filters. Combines French press body with pour-over clarity. BPA-free Tritan plastic.",
  },
  {
    name: "Chambord 8-Cup",
    brand: "Bodum",
    type: "french-press",
    material: "Glass",
    capacityMl: 1000,
    filterType: "metal",
    notes: "Classic French press design from the 1950s. Borosilicate glass with stainless steel frame. Produces full-bodied coffee. 34oz capacity.",
  },
  {
    name: "Chambord 4-Cup",
    brand: "Bodum",
    type: "french-press",
    material: "Glass",
    capacityMl: 500,
    filterType: "metal",
    notes: "Mid-size Chambord for 2-3 servings. 17oz capacity. Same iconic design with 3-part plunger system.",
  },
  {
    name: "Chambord 3-Cup",
    brand: "Bodum",
    type: "french-press",
    material: "Glass",
    capacityMl: 350,
    filterType: "metal",
    notes: "Personal-size French press. 12oz capacity. Made in Portugal.",
  },
  {
    name: "Espro P7",
    brand: "Espro",
    type: "french-press",
    material: "Stainless Steel",
    capacityMl: 950,
    filterType: "metal",
    notes: "Premium French press with double micro-mesh filters. Vacuum-insulated walls keep coffee hot. Produces cleaner cups than traditional French press.",
  },

  // Other Methods
  {
    name: "Moka Express 6-Cup",
    brand: "Bialetti",
    type: "other",
    material: "Aluminum",
    capacityMl: 300,
    filterType: "metal",
    notes: "Classic Italian stovetop espresso maker. Produces strong, concentrated coffee. 6-cup (300ml) capacity. Iconic octagonal design since 1933.",
  },
  {
    name: "Moka Express 3-Cup",
    brand: "Bialetti",
    type: "other",
    material: "Aluminum",
    capacityMl: 150,
    filterType: "metal",
    notes: "Compact 3-cup (150ml) Moka pot. Perfect for 1-2 servings of strong stovetop espresso.",
  },
];

// ============================================================================
// ELECTRIC GRINDERS - Top 20 Electric Coffee Grinders
// ============================================================================

export const electricGrindersData = [
  // Baratza
  {
    name: "Encore ESP",
    brand: "Baratza",
    model: "ZCG495",
    type: "electric",
    burrType: "conical",
    burrSize: 40,
    settingsMin: 1,
    settingsMax: 40,
    settingsType: "stepped",
    notes: "Entry-level espresso grinder with M2 steel burrs. Micro-steps 1-20 for espresso, macro-steps 21-40 for filter. 550 RPM, 70W. Range: 230-1380 microns.",
  },
  {
    name: "Virtuoso+",
    brand: "Baratza",
    model: "ZCG587",
    type: "electric",
    burrType: "conical",
    burrSize: 40,
    settingsMin: 1,
    settingsMax: 40,
    settingsType: "stepped",
    notes: "Premium home grinder with digital timer. European-made burrs. 550 RPM, 70W. Range: 200-1200 microns. Grinds 1.5-2.4g/sec.",
  },
  {
    name: "Vario+",
    brand: "Baratza",
    model: "ZCG586",
    type: "electric",
    burrType: "flat",
    burrSize: 54,
    settingsMin: 1,
    settingsMax: 230,
    settingsType: "stepped",
    notes: "Top-rated home grinder with 54mm ceramic flat burrs. 230 micro-adjustments. Low retention for single-dosing. Perfect 10/10 rating.",
  },
  {
    name: "Forte AP",
    brand: "Baratza",
    model: "ZCG1086",
    type: "electric",
    burrType: "flat",
    burrSize: 54,
    settingsMin: 1,
    settingsMax: 260,
    settingsType: "stepped",
    notes: "Commercial-grade with ceramic Ditting burrs. 260 settings. Range: 230-1150 microns. Metal portaholder and touchscreen.",
  },
  {
    name: "Sette 270Wi",
    brand: "Baratza",
    model: "ZCG11081",
    type: "electric",
    burrType: "conical",
    burrSize: 40,
    settingsMin: 1,
    settingsMax: 270,
    settingsType: "stepped",
    notes: "Innovative straight-through design with weight-based dosing. 270 micro-steps. Unique outer rotating ring burr for low retention.",
  },

  // Fellow
  {
    name: "Ode Brew Grinder Gen 2",
    brand: "Fellow",
    model: "D1211",
    type: "electric",
    burrType: "flat",
    burrSize: 64,
    settingsMin: 1,
    settingsMax: 31,
    settingsType: "stepped",
    notes: "Premium brew grinder with 64mm flat burrs. 31 settings optimized for filter methods. 1400 RPM PID-controlled motor. NOT for espresso. 100g single-dose hopper.",
  },
  {
    name: "Opus",
    brand: "Fellow",
    model: "OPUS-MB",
    type: "electric",
    burrType: "conical",
    burrSize: 40,
    settingsMin: 1,
    settingsMax: 41,
    settingsType: "stepped",
    notes: "Compact all-purpose grinder. 40mm burrs for espresso to cold brew. Quiet motor with timed auto-stop. Magnetic catch cup.",
  },

  // Eureka
  {
    name: "Mignon Specialita",
    brand: "Eureka",
    model: "E55S",
    type: "electric",
    burrType: "flat",
    burrSize: 55,
    settingsMin: 0,
    settingsMax: 999,
    settingsType: "stepless",
    notes: "Quiet espresso grinder with 55mm flat burrs and ACE anti-clump system. Silent Technology. 310W, 1350 RPM. Stepless micrometric adjustment. 1.8g/sec.",
  },
  {
    name: "Mignon Zero",
    brand: "Eureka",
    model: "E16Z",
    type: "electric",
    burrType: "flat",
    burrSize: 55,
    settingsMin: 0,
    settingsMax: 999,
    settingsType: "stepless",
    notes: "Single-dose champion with bellows. Near-zero retention. Silent Technology. Same 55mm burrs as Specialita.",
  },
  {
    name: "Mignon Crono",
    brand: "Eureka",
    model: "E16C",
    type: "electric",
    burrType: "flat",
    burrSize: 50,
    settingsMin: 0,
    settingsMax: 999,
    settingsType: "stepless",
    notes: "Entry-level Mignon with 50mm flat burrs. Time-based dosing. Great value for espresso grinding.",
  },
  {
    name: "Mignon Perfetto",
    brand: "Eureka",
    model: "E55P",
    type: "electric",
    burrType: "flat",
    burrSize: 55,
    settingsMin: 0,
    settingsMax: 999,
    settingsType: "stepless",
    notes: "Silent espresso grinder without touch display. 55mm Diamond Inside burrs. Excellent value.",
  },
  {
    name: "Mignon XL",
    brand: "Eureka",
    model: "E65XL",
    type: "electric",
    burrType: "flat",
    burrSize: 65,
    settingsMin: 0,
    settingsMax: 999,
    settingsType: "stepless",
    notes: "Large 65mm burrs for high-volume home use. Faster grinding at 2.5g/sec. Premium build quality.",
  },

  // Niche
  {
    name: "Zero",
    brand: "Niche",
    model: "NG63",
    type: "electric",
    burrType: "conical",
    burrSize: 63,
    settingsMin: 0,
    settingsMax: 50,
    settingsType: "stepless",
    notes: "Single-dose king with 63mm Mazzer burrs. Near-zero retention (<0.2g). 330 RPM geared motor. Oak accents. 72dB. Grinds 1g/sec.",
  },
  {
    name: "Duo",
    brand: "Niche",
    model: "NG64",
    type: "electric",
    burrType: "flat",
    burrSize: 63,
    settingsMin: 0,
    settingsMax: 50,
    settingsType: "stepless",
    notes: "Flat burr variant with 63mm SSP burrs. Optimized for filter and light roasts. Dual-purpose design.",
  },

  // DF64 / Turin
  {
    name: "DF64 Gen 2",
    brand: "Turin",
    model: "DF64-V2",
    type: "electric",
    burrType: "flat",
    burrSize: 64,
    settingsMin: 0,
    settingsMax: 999,
    settingsType: "stepless",
    notes: "Single-dose flat burr grinder. Compatible with SSP/Italmill burrs. 1400 RPM motor. Popular upgrade platform.",
  },
  {
    name: "DF83",
    brand: "Turin",
    model: "DF83",
    type: "electric",
    burrType: "flat",
    burrSize: 83,
    settingsMin: 0,
    settingsMax: 999,
    settingsType: "stepless",
    notes: "Large 83mm flat burrs for cafe-quality home grinding. Variable RPM. Premium single-doser.",
  },

  // Lagom / Option-O
  {
    name: "Lagom P64",
    brand: "Option-O",
    model: "P64",
    type: "electric",
    burrType: "flat",
    burrSize: 64,
    settingsMin: 0,
    settingsMax: 999,
    settingsType: "stepless",
    notes: "Ultra-premium 64mm flat burr grinder. Multiple burr options available. 400 RPM direct drive. Minimal retention.",
  },
  {
    name: "Lagom Mini",
    brand: "Option-O",
    model: "MINI",
    type: "electric",
    burrType: "conical",
    burrSize: 38,
    settingsMin: 0,
    settingsMax: 999,
    settingsType: "stepless",
    notes: "Compact single-dose grinder with premium 38mm burrs. Ultra-low retention. Travel-friendly.",
  },

  // Weber Workshops
  {
    name: "EG-1",
    brand: "Weber Workshops",
    model: "EG-1",
    type: "electric",
    burrType: "flat",
    burrSize: 83,
    settingsMin: 0,
    settingsMax: 999,
    settingsType: "stepless",
    notes: "Ultra-premium 83mm flat burr grinder. SSP burrs. 450 RPM DC motor. Onyx chassis. Industry reference standard.",
  },
];

// ============================================================================
// MANUAL GRINDERS - Top 25 Hand Coffee Grinders
// ============================================================================

export const manualGrindersData = [
  // Comandante
  {
    name: "C40 MK4",
    brand: "Comandante",
    model: "MK4",
    type: "hand",
    burrType: "conical",
    burrSize: 39,
    settingsMin: 0,
    settingsMax: 40,
    settingsType: "stepped",
    notes: "German-made with Nitro Blade high-nitrogen steel burrs. 30 microns/click. 40 clicks total. Dual bearings. Glass and polymer jars included. ~600g weight.",
  },
  {
    name: "C40 MK4 + Red Clix",
    brand: "Comandante",
    model: "MK4-RC",
    type: "hand",
    burrType: "conical",
    burrSize: 39,
    settingsMin: 0,
    settingsMax: 80,
    settingsType: "stepped",
    notes: "With Red Clix accessory for 15 microns/click precision. 80 effective steps. Essential for espresso dialing.",
  },

  // 1Zpresso
  {
    name: "K-Ultra",
    brand: "1Zpresso",
    model: "K-ULTRA",
    type: "hand",
    burrType: "conical",
    burrSize: 48,
    settingsMin: 0,
    settingsMax: 100,
    settingsType: "stepped",
    notes: "Flagship all-rounder with 48mm heptagonal K burrs. 20 microns/click. 100 clicks/rotation. External adjustment. Best for pour-over with espresso capability.",
  },
  {
    name: "J-Ultra",
    brand: "1Zpresso",
    model: "J-ULTRA",
    type: "hand",
    burrType: "conical",
    burrSize: 48,
    settingsMin: 0,
    settingsMax: 100,
    settingsType: "stepped",
    notes: "Espresso specialist with 48mm titanium-coated burrs. 8 microns/click - finest adjustment available. 100 clicks/rotation. Magnetic catch cup.",
  },
  {
    name: "K-Max",
    brand: "1Zpresso",
    model: "K-MAX",
    type: "hand",
    burrType: "conical",
    burrSize: 48,
    settingsMin: 0,
    settingsMax: 90,
    settingsType: "stepped",
    notes: "Premium pour-over grinder with 48mm K burrs. 22 microns/click. External numbered adjustment. 40g capacity.",
  },
  {
    name: "J-Max",
    brand: "1Zpresso",
    model: "J-MAX",
    type: "hand",
    burrType: "conical",
    burrSize: 48,
    settingsMin: 0,
    settingsMax: 90,
    settingsType: "stepped",
    notes: "Espresso-focused with 48mm titanium burrs. 8.8 microns/click. External magnetic adjustment dial.",
  },
  {
    name: "X-Ultra",
    brand: "1Zpresso",
    model: "X-ULTRA",
    type: "hand",
    burrType: "conical",
    burrSize: 40,
    settingsMin: 0,
    settingsMax: 100,
    settingsType: "stepped",
    notes: "Mid-range heptagonal burr grinder. 40mm burrs. Dual-bearing spindle. Magnetic catch cup. $169 value.",
  },
  {
    name: "Q2 S",
    brand: "1Zpresso",
    model: "Q2S",
    type: "hand",
    burrType: "conical",
    burrSize: 38,
    settingsMin: 0,
    settingsMax: 40,
    settingsType: "stepped",
    notes: "Compact travel grinder. 38mm seven-core burrs. Internal adjustment. Foldable handle. 20g capacity.",
  },
  {
    name: "ZP6 Special",
    brand: "1Zpresso",
    model: "ZP6",
    type: "hand",
    burrType: "conical",
    burrSize: 48,
    settingsMin: 0,
    settingsMax: 120,
    settingsType: "stepped",
    notes: "Pour-over specialist with unique ZP burr geometry. 120 clicks/rotation. Optimized for filter brewing clarity.",
  },

  // Timemore
  {
    name: "Chestnut C3",
    brand: "Timemore",
    model: "C3",
    type: "hand",
    burrType: "conical",
    burrSize: 38,
    settingsMin: 5,
    settingsMax: 36,
    settingsType: "stepped",
    notes: "Best-value manual grinder. 38mm S2C 660 steel burrs. 83 microns/click. For filter coffee. 20g capacity. Do not grind below 5 clicks.",
  },
  {
    name: "Chestnut C3S",
    brand: "Timemore",
    model: "C3S",
    type: "hand",
    burrType: "conical",
    burrSize: 38,
    settingsMin: 6,
    settingsMax: 36,
    settingsType: "stepped",
    notes: "Updated C3 with foldable handle and travel bag. 38mm S2C burrs. 25g capacity. Compact and portable.",
  },
  {
    name: "Chestnut C3 ESP",
    brand: "Timemore",
    model: "C3-ESP",
    type: "hand",
    burrType: "conical",
    burrSize: 38,
    settingsMin: 0,
    settingsMax: 36,
    settingsType: "stepped",
    notes: "Espresso-optimized C3 with 23 microns/click fine adjustment. S2C 660 burrs. Designed for espresso precision.",
  },
  {
    name: "Chestnut S3",
    brand: "Timemore",
    model: "S3",
    type: "hand",
    burrType: "conical",
    burrSize: 42,
    settingsMin: 0,
    settingsMax: 36,
    settingsType: "stepped",
    notes: "Flagship Timemore with 42mm S2C burrs. Premium materials and finish. Sophisticated design.",
  },
  {
    name: "Chestnut X",
    brand: "Timemore",
    model: "X",
    type: "hand",
    burrType: "conical",
    burrSize: 42,
    settingsMin: 0,
    settingsMax: 36,
    settingsType: "stepped",
    notes: "Premium design with E&B burrs. Folding handle. Quick-release mechanism. 25g capacity.",
  },
  {
    name: "Nano",
    brand: "Timemore",
    model: "NANO",
    type: "hand",
    burrType: "conical",
    burrSize: 38,
    settingsMin: 6,
    settingsMax: 36,
    settingsType: "stepped",
    notes: "Ultra-compact travel grinder. 38mm burrs. Integrated catch cup. Foldable handle. 15g capacity.",
  },

  // Kinu
  {
    name: "M47 Phoenix",
    brand: "Kinu",
    model: "M47-PHOENIX",
    type: "hand",
    burrType: "conical",
    burrSize: 47,
    settingsMin: 0,
    settingsMax: 999,
    settingsType: "stepless",
    notes: "German-engineered with 47mm Black Fusion steel burrs. Stepless adjustment. Premium build quality. 35g capacity.",
  },
  {
    name: "M47 Classic",
    brand: "Kinu",
    model: "M47-CLASSIC",
    type: "hand",
    burrType: "conical",
    burrSize: 47,
    settingsMin: 0,
    settingsMax: 999,
    settingsType: "stepless",
    notes: "Original M47 design with 47mm burrs. Stepless micrometric adjustment. All-metal construction.",
  },
  {
    name: "M47 Simplicity",
    brand: "Kinu",
    model: "M47-SIMP",
    type: "hand",
    burrType: "conical",
    burrSize: 47,
    settingsMin: 0,
    settingsMax: 999,
    settingsType: "stepless",
    notes: "Streamlined M47 variant. Same 47mm burrs. Simplified design at lower price point.",
  },

  // Helor
  {
    name: "Helor 101",
    brand: "Helor",
    model: "101",
    type: "hand",
    burrType: "conical",
    burrSize: 38,
    settingsMin: 0,
    settingsMax: 999,
    settingsType: "stepless",
    notes: "Taiwan-made with 38mm stainless burrs. Stepless adjustment. Contemporary design.",
  },
  {
    name: "Helor 106",
    brand: "Helor",
    model: "106",
    type: "hand",
    burrType: "conical",
    burrSize: 38,
    settingsMin: 0,
    settingsMax: 999,
    settingsType: "stepless",
    notes: "Upgraded 101 with improved burr design. Titanium-coated option available.",
  },

  // Others
  {
    name: "ROK GrinderGC",
    brand: "ROK",
    model: "GC",
    type: "hand",
    burrType: "conical",
    burrSize: 48,
    settingsMin: 0,
    settingsMax: 999,
    settingsType: "stepless",
    notes: "Large 48mm burrs with stepless adjustment. Matches ROK espresso maker aesthetic.",
  },
  {
    name: "Lido 3",
    brand: "Orphan Espresso",
    model: "LIDO3",
    type: "hand",
    burrType: "conical",
    burrSize: 48,
    settingsMin: 0,
    settingsMax: 999,
    settingsType: "stepless",
    notes: "American-made with 48mm Swiss Etzinger burrs. Stepless adjustment. Large capacity. Built like a tank.",
  },
  {
    name: "Lido ET",
    brand: "Orphan Espresso",
    model: "LIDO-ET",
    type: "hand",
    burrType: "conical",
    burrSize: 48,
    settingsMin: 0,
    settingsMax: 999,
    settingsType: "stepless",
    notes: "Travel version of Lido with same 48mm Swiss burrs. Collapsible handle.",
  },
  {
    name: "Porlex Mini II",
    brand: "Porlex",
    model: "MINI-II",
    type: "hand",
    burrType: "conical",
    burrSize: 30,
    settingsMin: 1,
    settingsMax: 13,
    settingsType: "stepped",
    notes: "Compact Japanese ceramic burr grinder. 13 click settings. 20g capacity. Fits inside AeroPress.",
  },
  {
    name: "Porlex Tall II",
    brand: "Porlex",
    model: "TALL-II",
    type: "hand",
    burrType: "conical",
    burrSize: 30,
    settingsMin: 1,
    settingsMax: 13,
    settingsType: "stepped",
    notes: "Larger Porlex with ceramic burrs. 30g capacity. Stainless steel body. Made in Japan.",
  },
];

// ============================================================================
// COSTCO WHOLE BEAN COFFEES
// ============================================================================

export const costcoCoffeesData = [
  // Kirkland Signature
  {
    name: "Colombian Supremo",
    roaster: "Kirkland Signature",
    origin: "Colombia",
    region: "Concordia",
    process: "washed",
    variety: "Castillo",
    roastLevel: "medium",
    flavorNotes: ["tropical fruit", "molasses", "cocoa", "spicy floral"],
    notes: "Large, high-quality Supremo grade beans. Smooth flavor with syrupy texture. Previously roasted by Starbucks, now by Rogers Family Co. 3 lb bag.",
  },
  {
    name: "House Blend",
    roaster: "Kirkland Signature",
    origin: "Multi-origin",
    region: null,
    process: "washed",
    variety: null,
    roastLevel: "medium",
    flavorNotes: ["balanced", "smooth", "nutty"],
    notes: "Balanced and smooth everyday coffee. 2.5 lb bag. Great value at $12.99. Roasted in USA.",
  },
  {
    name: "Espresso Blend",
    roaster: "Kirkland Signature",
    origin: "Multi-origin",
    region: null,
    process: "washed",
    variety: null,
    roastLevel: "dark",
    flavorNotes: ["rich", "intense", "dark chocolate"],
    notes: "Rich and intense dark roast designed for espresso. 2.5 lb bag. Roasted in USA.",
  },
  {
    name: "French Roast",
    roaster: "Kirkland Signature",
    origin: "Multi-origin",
    region: null,
    process: "washed",
    variety: null,
    roastLevel: "dark",
    flavorNotes: ["smoky", "bold", "dark chocolate"],
    notes: "Bold, smoky dark roast. 2.5 lb bag. Full-bodied with low acidity.",
  },
  {
    name: "Decaf House Blend",
    roaster: "Kirkland Signature",
    origin: "Multi-origin",
    region: null,
    process: "washed",
    variety: null,
    roastLevel: "medium",
    flavorNotes: ["balanced", "smooth"],
    notes: "Water-process decaffeinated. Medium roast. 2.5 lb bag. No harsh chemicals used in decaf process.",
  },
  {
    name: "Organic Colombian Decaf",
    roaster: "Kirkland Signature",
    origin: "Colombia",
    region: null,
    process: "washed",
    variety: null,
    roastLevel: "medium-dark",
    flavorNotes: ["smooth", "balanced"],
    notes: "USDA Organic certified. Water-process decaffeinated. 2 lb bag.",
  },
  {
    name: "Organic Ethiopia",
    roaster: "Kirkland Signature",
    origin: "Ethiopia",
    region: null,
    process: "natural",
    variety: "Heirloom",
    roastLevel: "medium",
    flavorNotes: ["blueberry", "floral", "bright"],
    notes: "USDA Organic single-origin Ethiopian. Bright and fruity. 2 lb bag.",
  },
  {
    name: "Organic Sumatra",
    roaster: "Kirkland Signature",
    origin: "Indonesia",
    region: "Sumatra",
    process: "wet-hulled",
    variety: null,
    roastLevel: "dark",
    flavorNotes: ["earthy", "herbal", "full body"],
    notes: "USDA Organic Indonesian coffee. Earthy, full-bodied. 2 lb 2-pack.",
  },
  {
    name: "Organic Whole Bean Blend",
    roaster: "Kirkland Signature",
    origin: "Multi-origin",
    region: null,
    process: "washed",
    variety: null,
    roastLevel: "medium",
    flavorNotes: ["balanced", "smooth"],
    notes: "USDA Organic blend. 2 lb 2-pack.",
  },

  // Starbucks (at Costco)
  {
    name: "Pike Place Roast",
    roaster: "Starbucks",
    origin: "Multi-origin",
    region: "Latin America",
    process: "washed",
    variety: null,
    roastLevel: "medium",
    flavorNotes: ["cocoa", "praline", "smooth"],
    notes: "Starbucks flagship medium roast. Well-rounded and smooth. 2.5 lb bag at Costco.",
  },
  {
    name: "French Roast",
    roaster: "Starbucks",
    origin: "Multi-origin",
    region: null,
    process: "washed",
    variety: null,
    roastLevel: "dark",
    flavorNotes: ["smoky", "intense", "bold"],
    notes: "Starbucks darkest roast. Smoky and intense. 2.5 lb bag.",
  },
  {
    name: "Espresso Roast",
    roaster: "Starbucks",
    origin: "Multi-origin",
    region: null,
    process: "washed",
    variety: null,
    roastLevel: "dark",
    flavorNotes: ["caramel", "molasses", "rich"],
    notes: "Starbucks espresso blend. Rich and caramelly. Available at Costco.",
  },

  // Peet's Coffee
  {
    name: "Major Dickason's Blend",
    roaster: "Peet's Coffee",
    origin: "Multi-origin",
    region: null,
    process: "washed",
    variety: null,
    roastLevel: "dark",
    flavorNotes: ["full-bodied", "complex", "rich"],
    notes: "Peet's flagship blend. Complex and full-bodied. 2 lb bag. 4.8/5 stars from 2,357 reviews.",
  },
  {
    name: "French Roast",
    roaster: "Peet's Coffee",
    origin: "Multi-origin",
    region: null,
    process: "washed",
    variety: null,
    roastLevel: "dark",
    flavorNotes: ["smoky", "bold", "bittersweet"],
    notes: "Very dark roast from SF's original specialty roaster. 2 lb bag.",
  },

  // Jose's Gourmet Coffee
  {
    name: "100% Organic Mayan",
    roaster: "Jose's Gourmet Coffee",
    origin: "Mexico/Guatemala",
    region: "Chiapas",
    process: "washed",
    variety: null,
    roastLevel: "medium",
    flavorNotes: ["nutty", "cocoa", "mild"],
    notes: "USDA Organic certified. Mild and smooth. 2.5 lb bag for $8.99 - incredible value. 4.6/5 stars.",
  },
  {
    name: "100% Colombian Supremo",
    roaster: "Jose's Gourmet Coffee",
    origin: "Colombia",
    region: null,
    process: "washed",
    variety: null,
    roastLevel: "medium",
    flavorNotes: ["balanced", "mild", "clean"],
    notes: "Colombian single-origin. 2.5 lb bag at Costco.",
  },

  // Lavazza
  {
    name: "Qualità Oro",
    roaster: "Lavazza",
    origin: "Multi-origin",
    region: "Central/South America",
    process: "washed",
    variety: null,
    roastLevel: "medium",
    flavorNotes: ["aromatic", "floral", "honey"],
    notes: "Italian premium blend. 100% Arabica. Ideal for espresso. Smooth, full-bodied.",
  },
  {
    name: "Super Crema",
    roaster: "Lavazza",
    origin: "Multi-origin",
    region: null,
    process: "washed",
    variety: null,
    roastLevel: "medium",
    flavorNotes: ["hazelnut", "brown sugar", "creamy"],
    notes: "Creamy espresso blend. Popular at Costco for home espresso machines.",
  },
  {
    name: "Dek Decaf",
    roaster: "Lavazza",
    origin: "Multi-origin",
    region: null,
    process: "washed",
    variety: null,
    roastLevel: "medium",
    flavorNotes: ["smooth", "balanced"],
    notes: "Lavazza's decaf blend. Good option for decaf espresso.",
  },

  // San Francisco Bay
  {
    name: "French Roast",
    roaster: "San Francisco Bay",
    origin: "Multi-origin",
    region: null,
    process: "washed",
    variety: null,
    roastLevel: "dark",
    flavorNotes: ["smoky", "bold", "dark chocolate"],
    notes: "Family-owned SF Bay roaster. Bold French roast. Available in bulk at Costco.",
  },
  {
    name: "Fog Chaser",
    roaster: "San Francisco Bay",
    origin: "Multi-origin",
    region: null,
    process: "washed",
    variety: null,
    roastLevel: "medium-dark",
    flavorNotes: ["smooth", "cocoa", "caramel"],
    notes: "Popular SF Bay blend. Smooth and approachable. 2 lb bag.",
  },

  // Mayorga
  {
    name: "Café Cubano Dark Roast",
    roaster: "Mayorga",
    origin: "Peru/Honduras/Nicaragua",
    region: null,
    process: "washed",
    variety: null,
    roastLevel: "dark",
    flavorNotes: ["bold", "smoky", "sweet"],
    notes: "USDA Organic, Non-GMO, OU Kosher. 100% Arabica. 4.7/5 stars from 2,600+ reviews. Best whole bean at Costco according to rankings.",
  },
  {
    name: "Café Cubano Medium Roast",
    roaster: "Mayorga",
    origin: "Latin America",
    region: null,
    process: "washed",
    variety: null,
    roastLevel: "medium",
    flavorNotes: ["smooth", "sweet", "balanced"],
    notes: "USDA Organic. Lighter take on the Cubano blend. Available at Costco.",
  },
];

// ============================================================================
// EXPORT SUMMARY
// ============================================================================
//
// To seed your database, navigate to /settings/seed in the app while logged in.
//
// Data Summary:
// - 20 Brewers (Pour-over, Immersion, French Press, Moka)
// - 20 Electric Grinders (Baratza, Fellow, Eureka, Niche, etc.)
// - 25 Manual Grinders (Comandante, 1Zpresso, Timemore, Kinu, etc.)
// - 24 Costco Coffees (Kirkland, Starbucks, Peet's, Jose's, Lavazza, etc.)
//
// Sources researched:
// - Official manufacturer websites (Hario, Chemex, Baratza, Fellow, etc.)
// - Prima Coffee Equipment specifications
// - Coffee Chronicler reviews
// - CoffeeGeek guides
// - Honest Coffee Guide grind settings
// - Costco.com product listings
// - Tasting Table coffee rankings
